$keys = "HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\grouppolicy\{35378eac-683f-11d2-a89a-00c04fbbcfa2}\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\wdi\{9c5a40da-b965-4fc3-8781-88dd50a6299d}\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\power\powersettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\assistance\client\1.0\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\securepipeservers\winreg\allowedexactpaths\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\securepipeservers\winreg\allowedpaths\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\appcompat\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\eventlog\application\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\appx\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\attachments\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\system\audit\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\biometrics\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\winrm\client\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\credui\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\credui\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\cryptography\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\controlpanel\desktop\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\devicemetadata\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\driversearching\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\policies\earlylaunch\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\eventviewer\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\explorer\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\explorer\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\internetexplorer\feeds\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\lsa\fipsalgorithmpolicy\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\handwritingerrorreports\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\installer\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\controlpanel\international\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\tcpip\v6transition\iphttps\iphttpsinterface\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\ipsec\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\sessionmanager\kernel\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\lanmanworkstation\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\ldap\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\lltd\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\locationandsensors\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\lsa\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\mrxsmb10\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\lsa\msv1_0\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\networkconnections\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\tcpip\parameters\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\system\kerberos\parameters\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\netbt\parameters\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\lanmanworkstation\parameters\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\tcpip6\parameters\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\netlogon\parameters\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\lanmanserver\parameters\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\peernet\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\personalization\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\lsa\pku2u\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\scripteddiagnosticsprovider\policy\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsnt\printers\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\currentversion\pushnotifications\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\wcn\registrars\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsnt\rpc\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\powershell\scriptblocklogging\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\services\eventlog\security\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\eventlog\security\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\print\providers\lanmanprintservices\servers\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\winrm\service\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\servicing\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\sessionmanager\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\deviceinstall\settings\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\eventlog\setup\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsdefender\spynet\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\sessionmanager\subsystems\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\system\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\system\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\eventlog\system\",
"HKEY_LOCAL_MACHINE\software\microsoft\windows\currentversion\policies\system",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsnt\terminalservices\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\wcn\ui\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windows\tcpip\v6transition\",
"HKEY_LOCAL_MACHINE\system\currentcontrolset\control\securityproviders\wdigest\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\sqmclient\windows\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsmediaplayer\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsstore\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\windowsstore\windowsupdate\",
"HKEY_LOCAL_MACHINE\software\microsoft\windowsnt\currentversion\winlogon\",
"HKEY_LOCAL_MACHINE\software\policies\microsoft\wmdrm\"

$tempFolder = 'K:\reg_keys\'
$outputFile = 'K:\reg_keys\reg_keys.reg'

$keys | % {
  $i++
  & reg export $_ "$tempFolder\$i.reg"
}

'Windows Registry Editor Version 5.00' | Set-Content $outputFile
(Get-Content "$tempFolder\*.reg") | ? {
  $_ -ne 'Windows Registry Editor Version 5.00'
} | Add-Content $outputFile

Remove-Item -recurse $tempFolder\* -exclude reg_keys.reg
